# Generated by Django 5.1.6 on 2025-03-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_orderlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Mobile', models.IntegerField(max_length=10, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('NL', models.CharField(max_length=150, null=True)),
                ('OS', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
